# This is the template for suggesting a mod to be added to the modpack
# https://www.youtube.com/watch?v=JnSAHjMCkQQ
name: "Mod Request"
description: Suggest a mod to be added to the modpack
title: "[MOD REQUEST] <Mod Name>"
labels: [":sparkles: mod request"]
#assignees: '' # Update with auto-assignees
body:
  -  type: input
     id: mod_name
     attributes:
       label: Mod Name
       description: Name of the mod you're suggesting
       placeholder: Example Mod
     validations:
       required: true

  -  type: checkboxes
     id: mods_request
     attributes:
      label: Mod Request Agreement
      description: I understand that this is a request and not a guarantee that the mod will be added to the modpack.
      options:
        - label: 'I understand'
          required: true

  - type: checkboxes
    id: mods_votes
    attributes:
      label: Mod Voting Agreement
      description: I understand that if this mod is already in the mods list, I can vote for it by creating a new request.
      options:
        - label: 'I understand'
          required: true

  - type: textarea
    id: mod_link
    attributes:
      label: Mod Link
      description: A link to where the mod can be downloaded or more information can be found.
      placeholder: https://appliedenergistics.org
    validations:
      required: true

  - type: textarea
    id: mod_cfapi_link
    attributes:
      label: Mod CurseForge Link
      description: A link to the CurseForge repository where the mod can be downloaded or more information can be found.
      placeholder: https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: The version of the mod you're suggesting
      placeholder: 7.0.5
    validations:
      required: true

  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft Version
      description: The version of Minecraft you wish to play with this mod.
      multiple: false
      options:
        - '1.12'
        - '1.13'
        - '1.14'
        - '1.15'
        - '1.16'
        - '1.17'
        - '1.18'
        - '1.19'
        - '1.20'
        - '1.21'
      default: 3
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Explain why you think this mod should be included in the modpack or why you want to play with it.
      placeholder: This mod adds a lot of new content to the game and enhances the player experience
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any additional notes or comments
      placeholder: This mod requires a specific version of Forge to work correctly
