name: Mod Addon Classifier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  classify-mods-addons:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Run ModAddonClassifier
      run: python .github/scripts/mod_addon_classifier.py

    - name: Output results
      run: |
        echo "Updated modslist.json:"
        cat modslist.json