name: Mod Request Handler

on:
  issues:
    types: [opened, edited]

jobs:
  handle_mod_request:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Mod Request')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Handle Mod Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      run: python .github/scripts/handle_mod_request.py "${{ github.event.issue.number }}"