name: Only Dev to Main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  only-dev-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug GitHub context
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF: ${{ github.base_ref }}"

      - name: Add comment if branch check fails on pull request
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentMessage = "Error: Only PRs from the 'dev' branch can be merged into 'main'!";
            const prContext = github.context;
            const { owner, repo, number } = prContext.issue;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            octokit.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: commentMessage
            });
