name: Only Dev to Main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
permissions:
  issues: write
    
jobs:
  only-dev-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug GitHub context
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF: ${{ github.base_ref }}"

      - name: Add comment if branch check fails on pull request
        if: ${{ github.head_ref != 'dev' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentMessage = "Error: Only PRs from the 'dev' branch can be merged into 'main'!";
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: commentMessage
            });
      - name: Fail if not from dev branch
        if: ${{ github.head_ref != 'dev' }}
        run: exit 1
