name: Only Dev to Main

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  only-dev-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug GitHub context
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF: ${{ github.base_ref }}"

      - name: Check if PR is to main from dev
        id: check_pr
        run: |
          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" != "dev" ]]; then
            echo "Only the 'dev' branch can create a pull request to 'main'"
            exit 1
          else
            echo "Target is not 'main' or PR is from 'dev', skipping check."
          fi

      - name: Add comment if branch check fails on pull request
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = "Error: You shall not create a pull request to 'main'!";
            const context = github.context;
            const { owner, repo, number } = context.issue;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            octokit.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: message
            });
