name: Check Repetitions

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies [Collections]
      run: pip install collections-extended
    
    - name: Install dependencies [Requests]
      run: pip install requests


    - name: Run Python script
      run: python ./test/names_repetition/verify_rep_names.py
            